uint64 id
osi3_bridge/Dimension3d dimension
geometry_msgs/Vector3 position
osi3_bridge/Orientation3d orientation
geometry_msgs/Vector3 velocity
geometry_msgs/Vector3 acceleration
uint8 type

uint8 TYPE_UNKNOWN = 0
uint8 TYPE_OTHER = 1
uint8 TYPE_CAR = 2
uint8 TYPE_PEDESTRIAN = 3
uint8 TYPE_ANIMAL = 4
uint8 TYPE_TRUCK = 5
uint8 TYPE_TRAILER = 6
uint8 TYPE_MOTORBIKE = 7
uint8 TYPE_BICYCLE = 8
uint8 TYPE_BUS = 9
uint8 TYPE_TRAM = 10
uint8 TYPE_TRAIN = 11
uint8 TYPE_WHEELCHAIR = 12

